In [16]:
import pandas as pd

# Load the uploaded CSV file to check its structure and content
file_path = 'nutrition.csv'
data = pd.read_csv(file_path)

# Display the first few rows of the dataset
data.head()

,Public Food Key,Classification,Food Name,Classification Name,Food Description,"Energy with dietary fibre, equated \n(kJ)","Energy, without dietary fibre, equated \n(kJ)",Moisture (water) \n(g),Protein \n(g),Nitrogen \n(g),...,Leucine \n(mg),Lysine \n(mg),Methionine \n(mg),Phenylalanine \n(mg),Proline \n(mg),Serine \n(mg),Threonine \n(mg),Tyrosine \n(mg),Tryptophan \n(mg),Valine \n(mg)
0,F000002,15202.0,"Abalone, black lip, aquacultured, raw","Molluscs, fresh, frozen",Uncooked greyish-brown flesh of a single-shell...,332,332,76.6,16.2,2.60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,182.0,NaN
1,F000003,15202.0,"Abalone, black lip, wild, raw","Molluscs, fresh, frozen",Uncooked greyish-brown flesh of a single-shell...,380,380,75.6,19.4,3.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,218.0,NaN
2,F000004,15202.0,"Abalone, brown lip, wild, raw","Molluscs, fresh, frozen",Uncooked greyish-brown flesh of a single-shell...,352,352,78.8,17.8,2.86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200.0,NaN
3,F000005,15202.0,"Abalone, green lip, aquacultured, raw","Molluscs, fresh, frozen",Uncooked greyish-brown flesh of a single-shell...,345,345,75.2,17.1,2.73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,192.0,NaN
4,F000006,15202.0,"Abalone, green lip, wild, raw","Molluscs, fresh, frozen",Uncooked greyish-brown flesh of a single-shell...,363,363,74.0,18.7,2.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,209.0,NaN

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Define the columns to search in
search_columns = ['Food Name', 'Food Description']

# Combine the relevant columns into a single searchable text for each row
data['search_text'] = data[search_columns].fillna('').apply(' '.join, axis=1)

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(data['search_text'])

In [29]:
def search(query):
    # Compute TF-IDF for the dataset and the query
    query_vector = vectorizer.transform([query])

    # Compute cosine similarity between the query and all rows
    cosine_similarities = cosine_similarity(query_vector, tfidf_matrix).flatten()

    # Get the index of the most similar row
    most_similar_idx = cosine_similarities.argmax()
    most_similar_row = data.iloc[most_similar_idx]

    # Display the most relevant result
    return most_similar_row[['Public Food Key', 'Food Name', 'Classification Name', 'Food Description']]

In [34]:
search("QUICK EZE ORIGINAL 60 TAB")

Public Food Key                                                  F001152
Food Name                          Biscuit, savoury, rice cracker, plain
Classification Name    Savoury biscuits, rice based (includes rice ca...
Food Description       Commercially prepared savoury biscuit made pre...
Name: 222, dtype: object